import { images } from "@/config/image";

export const CATEGORY_MAP = {
  sparklers: {
    key: "sparklers",
    name: "Sparklers",
    ta: "மத்தாப்புகள்",
    image: images.sparklers,
    description: "Electric, Green, Red, and Giant 50cm & 75cm Sparklers"
  },
  ground: {
    key: "ground",
    name: "Ground Chakkars",
    ta: "தரைச் சக்கரம்",
    image: images.groundChakkar,
    description: "Big, Asoka, Special, Deluxe, Wire and Lotus spinning wheels"
  },
  flower: {
    key: "flower",
    name: "Flower Pots",
    ta: "பூச்சட்டி",
    image: images.flowerPot,
    description: "Small, Big, Special, Ashoka UV, Giant and Colour Kotti pots"
  },
  fountain: {
    key: "fountain",
    name: "Fountains",
    ta: "ஃபவுண்டன்",
    image: images.fountain,
    description: "Multi-color, Peacock, Twix, 4 inch Mega and Tri-colour fountains"
  },
  kids: {
    key: "kids",
    name: "Kids Special",
    ta: "குழந்தைகள் ஸ்பெஷல்",
    image: images.kidsCrackers,
    description: "Butterflies, Bambaram, Helicopters, Siren, Pop-pops & Snake tablets"
  },
  pencils: {
    key: "pencils",
    name: "Twinkling Stars & Pencils",
    ta: "ட்விங்க்ளிங் ஸ்டார் & பென்சில்",
    image: images.pencils,
    description: "Twinkling stars, 7cm pencils, Colour crush and Navrang 3-colour pencils"
  },
  sound: {
    key: "sound",
    name: "Single Sound Crackers",
    ta: "சவுண்ட் வெடி / லட்சுமி",
    image: images.laxmiSound,
    description: "Kuruvai, 3.5 & 4 inch Laxmi, Two Sound, Red Bijili and Giant Chorsa"
  },
  deluxe: {
    key: "deluxe",
    name: "Deluxe Crackers",
    ta: "டீலக்ஸ் வெடிகள்",
    image: images.laxmiSound,
    description: "24, 50, and 100 Deluxe high decibel sound crackers"
  },
  bomb: {
    key: "bomb",
    name: "Bomb Varieties",
    ta: "பாம் வகைகள்",
    image: images.atomBomb,
    description: "Hydro Bomb, King of King, Classic, Titan, Dinosaur & Digital bomb"
  },
  sky: {
    key: "sky",
    name: "Sky Shots",
    ta: "ஸ்கை ஷாட்ஸ்",
    image: images.aerialSkyShot,
    description: "7 Shots, 10 Pcs Colour Shots, Penta 5 Colour and Chotta Fancy"
  },
  ayya: {
    key: "ayya",
    name: "Ayya Fire Works",
    ta: "அய்யா ஃபயர் ஒர்க்ஸ்",
    image: images.pipesShells,
    description: "Ulta Pulta, Colour Fantasy, Lotus Wheel, Roopkheela & Pipes"
  },
  sonny: {
    key: "sonny",
    name: "Sonny Fire Works",
    ta: "சன்னி ஃபயர் ஒர்க்ஸ்",
    image: images.multishot,
    description: "Colour Pinjor Kotti, Blue Heaven, 4 inch Great Wall & Happy New Year family"
  },
  srivijay: {
    key: "srivijay",
    name: "Sri Vijay Fire Works",
    ta: "ஸ்ரீ விஜய் ஃபயர் ஒர்க்ஸ்",
    image: images.flowerPot,
    description: "Giant Multi Colour Flower Pots, 4 & 5 Pipe varieties, Wow Pink & Orange"
  },
  rocket: {
    key: "rocket",
    name: "Rocket Varieties",
    ta: "ராக்கெட் வகைகள்",
    image: images.rockets,
    description: "Lunix Rocket, 2 Sound Rocket and Whistling high altitude Rockets"
  },
  pipe: {
    key: "pipe",
    name: "Pipe Varieties",
    ta: "பைப் வகைகள்",
    image: images.pipesShells,
    description: "1.75 inch, 2 inch, 2 Pipe 6 Varieties and 2/3 Step aerial pipes"
  },
  multishot: {
    key: "multishot",
    name: "Multi Colour Shots",
    ta: "மல்டி கலர் ஷாட்ஸ் கேக்",
    image: images.multishot,
    description: "12, 25, 30, 60, 120, 240 and 500 Grand Repeating Aerial Cakes"
  },
  matches: {
    key: "matches",
    name: "Colour Matches",
    ta: "கலர் தீக்குச்சி",
    image: images.colorMatches,
    description: "Max 3 in 1 Cone Ramesh and V.I.P 10 in 1 Laptop Mega color matches"
  },
  gift: {
    key: "gift",
    name: "Diwali Gift Boxes",
    ta: "கிஃப்ட் பாக்ஸ் காம்போ",
    image: images.giftBox,
    description: "21, 25, 30, 40, 45 and 50 Items assorted family Diwali Gift Boxes"
  },
  series: {
    key: "series",
    name: "Garland K Series",
    ta: "சீரிஸ் / வாலா வெடி",
    image: images.garlandLadi,
    description: "100, 200, 1K (1000 wala), 2K, 5K and 10K giant traditional garland ladi"
  },
  paper: {
    key: "paper",
    name: "Paper Bomb",
    ta: "பேப்பர் பாம் / காகித வெடி",
    image: images.paperBomb,
    description: "Paper Bomb Small 1/4, Medium 1/2, and Mega 1 sound crackers"
  },
  toy: {
    key: "toy",
    name: "Toy Pistol & Caps",
    ta: "டாய் பிஸ்டல் & துப்பாக்கி",
    image: images.toyCapGun,
    description: "Ring Gun, Ring Caps, Roll Caps, Ziraffe, Gusher, Spencer & Dragon pistols"
  }
};

export const CATEGORY_KEYS = Object.keys(CATEGORY_MAP);

export const PRODUCTS = [
  { "id": 1, "name": "7 cm Electric Sparklers", "ta": "7 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 8, "full": 32, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 2, "name": "10 cm Electric Sparklers", "ta": "10 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 20, "full": 80, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 3, "name": "12 cm Electric Sparklers", "ta": "12 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 26, "full": 104, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 4, "name": "12 cm Green Sparklers", "ta": "12 செ.மீ. பச்சை கம்பி மத்தாப்பு", "price": 32, "full": 128, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 5, "name": "12 cm Red Sparklers", "ta": "12 செ.மீ. சிவப்பு கம்பி மத்தாப்பு", "price": 35, "full": 140, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 6, "name": "15 cm Electric Sparklers", "ta": "15 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 45, "full": 180, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 7, "name": "15 cm Green Sparklers", "ta": "15 செ.மீ. பச்சை கம்பி மத்தாப்பு", "price": 60, "full": 240, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 8, "name": "15 cm Red Sparklers", "ta": "15 செ.மீ. சிவப்பு கம்பி மத்தாப்பு", "price": 65, "full": 260, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 9, "name": "30 cm Electric Sparklers", "ta": "30 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 45, "full": 180, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 10, "name": "30 cm Green Sparklers", "ta": "30 செ.மீ. பச்சை கம்பி மத்தாப்பு", "price": 60, "full": 240, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 11, "name": "30 cm Red Sparklers", "ta": "30 செ.மீ. சிவப்பு கம்பி மத்தாப்பு", "price": 65, "full": 260, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 12, "name": "30 cm V.I.P. Gold 5 in 1 Sparklers", "ta": "30 செ.மீ. V.I.P. கோல்ட் 5 இன் 1 மத்தாப்பு", "price": 80, "full": 320, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 13, "name": "10 cm 5 in 1 Rainbow Colours Laptop", "ta": "10 செ.மீ. 5 இன் 1 ரெயின்போ கலர்ஸ் லேப்டாப்", "price": 240, "full": 960, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 14, "name": "50 cm Electric Sparklers", "ta": "50 செ.மீ. மின்சார கம்பி மத்தாப்பு", "price": 170, "full": 680, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 15, "name": "50 cm Electric Sparklers Ramesh", "ta": "50 செ.மீ. எலக்ட்ரிக் மத்தாப்பு ரமேஷ்", "price": 240, "full": 960, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 16, "name": "50 cm 5 in 1 HiTek Gold Ramesh", "ta": "50 செ.மீ. 5 இன் 1 ஹைடெக் கோல்ட் ரமேஷ்", "price": 310, "full": 1240, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 17, "name": "75 cm Electric Sparklers Ramesh", "ta": "75 செ.மீ. மின்சார மத்தாப்பு ரமேஷ்", "price": 365, "full": 1460, "cat": "sparklers", "tag": "RRR 2026" },
  { "id": 18, "name": "Ground Chakkar Big", "ta": "தரைச் சக்கரம் பிக்", "price": 35, "full": 140, "cat": "ground", "tag": "RRR 2026" },
  { "id": 19, "name": "Ground Chakkar Asoka", "ta": "தரைச் சக்கரம் அசோகா", "price": 68, "full": 272, "cat": "ground", "tag": "RRR 2026" },
  { "id": 20, "name": "Ground Chakkar Asoka Jenis", "ta": "தரைச் சக்கரம் அசோகா ஜெனிஸ்", "price": 105, "full": 420, "cat": "ground", "tag": "RRR 2026" },
  { "id": 21, "name": "Ground Chakkar Special TVK/Prime/Celebrity", "ta": "தரைச் சக்கரம் ஸ்பெஷல் TVK/பிரைம்/செலிபிரிட்டி", "price": 110, "full": 440, "cat": "ground", "tag": "RRR 2026" },
  { "id": 22, "name": "Ground Chakkar Special Jenis", "ta": "தரைச் சக்கரம் ஸ்பெஷல் ஜெனிஸ்", "price": 105, "full": 420, "cat": "ground", "tag": "RRR 2026" },
  { "id": 23, "name": "Ground Chakkar Deluxe TVK/Prime", "ta": "தரைச் சக்கரம் டீலக்ஸ் TVK/பிரைம்", "price": 180, "full": 720, "cat": "ground", "tag": "RRR 2026" },
  { "id": 24, "name": "Spinner Special", "ta": "ஸ்பின்னர் ஸ்பெஷல்", "price": 180, "full": 720, "cat": "ground", "tag": "RRR 2026" },
  { "id": 25, "name": "Spinner Deluxe", "ta": "ஸ்பின்னர் டீலக்ஸ்", "price": 240, "full": 960, "cat": "ground", "tag": "RRR 2026" },
  { "id": 26, "name": "Wire Chakkar", "ta": "வயர் சக்கரம்", "price": 160, "full": 640, "cat": "ground", "tag": "RRR 2026" },
  { "id": 27, "name": "4x4 Wheel Lotus", "ta": "4x4 வீல் லோட்டஸ்", "price": 210, "full": 840, "cat": "ground", "tag": "RRR 2026" },
  { "id": 28, "name": "Ring O Ring", "ta": "ரிங் ஓ ரிங்", "price": 220, "full": 880, "cat": "ground", "tag": "RRR 2026" },
  { "id": 29, "name": "Flower Pots Small", "ta": "பூச்சட்டி ஸ்மால்", "price": 55, "full": 220, "cat": "flower", "tag": "RRR 2026" },
  { "id": 30, "name": "Flower Pot Big", "ta": "பூச்சட்டி பிக்", "price": 78, "full": 312, "cat": "flower", "tag": "RRR 2026" },
  { "id": 31, "name": "Flower Pots Special", "ta": "பூச்சட்டி ஸ்பெஷல்", "price": 120, "full": 480, "cat": "flower", "tag": "RRR 2026" },
  { "id": 32, "name": "Flower Pots Ashoka UV", "ta": "பூச்சட்டி அசோகா UV", "price": 150, "full": 600, "cat": "flower", "tag": "RRR 2026" },
  { "id": 33, "name": "Flower Pots Gaint", "ta": "பூச்சட்டி ஜெயண்ட்", "price": 190, "full": 760, "cat": "flower", "tag": "RRR 2026" },
  { "id": 34, "name": "Colour Kotti", "ta": "கலர் கொட்டி", "price": 210, "full": 840, "cat": "flower", "tag": "RRR 2026" },
  { "id": 35, "name": "Colour Kotti Premium", "ta": "கலர் கொட்டி பிரீமியம்", "price": 250, "full": 1000, "cat": "flower", "tag": "RRR 2026" },
  { "id": 36, "name": "Colour Kotti Deluxe", "ta": "கலர் கொட்டி டீலக்ஸ்", "price": 345, "full": 1380, "cat": "flower", "tag": "RRR 2026" },
  { "id": 37, "name": "Cosmic Pots or Jumbo Pots", "ta": "காஸ்மிக் பாட்ஸ் / ஜம்போ பாட்ஸ்", "price": 470, "full": 1880, "cat": "flower", "tag": "RRR 2026" },
  { "id": 38, "name": "Star Pots / Tango Shower", "ta": "ஸ்டார் பாட்ஸ் / டாங்கோ ஷவர்", "price": 100, "full": 400, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 39, "name": "Colour Rain / Peacock Feather", "ta": "கலர் ரெயின் / பீகாக் பெதர்", "price": 110, "full": 440, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 40, "name": "2 inch Fountain Red Green White Yellow", "ta": "2 இன்ச் ஃபவுண்டன் சிவப்பு பச்சை வெள்ளை மஞ்சள்", "price": 190, "full": 760, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 41, "name": "3 inch Fountain Twix / Power Pot", "ta": "3 இன்ச் ஃபவுண்டன் ட்விக்ஸ் / பவர் பாட்", "price": 230, "full": 920, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 42, "name": "4 inch Fountain Mega", "ta": "4 இன்ச் ஃபவுண்டன் மெகா", "price": 230, "full": 920, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 43, "name": "Tin 3 in 1", "ta": "டின் 3 இன் 1", "price": 300, "full": 1200, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 44, "name": "Mega Tri Colour Fountain Deluxe", "ta": "மெகா ட்ரை கலர் ஃபவுண்டன் டீலக்ஸ்", "price": 350, "full": 1400, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 45, "name": "Majical Peacock Tri Colour", "ta": "மேஜிக்கல் பீகாக் ட்ரை கலர்", "price": 140, "full": 560, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 46, "name": "Bada Peacock Multi Colour", "ta": "படா பீகாக் மல்டி கலர்", "price": 420, "full": 1680, "cat": "fountain", "tag": "RRR 2026" },
  { "id": 47, "name": "Emu Egg or Fire Egg", "ta": "ஈமு எக் / ஃபயர் எக்", "price": 200, "full": 800, "cat": "kids", "tag": "RRR 2026" },
  { "id": 48, "name": "Chit Pult Small", "ta": "சிட் புல்ட் ஸ்மால்", "price": 35, "full": 140, "cat": "kids", "tag": "RRR 2026" },
  { "id": 49, "name": "Kit Kat or Tim Tom Big", "ta": "கிட் கேட் / டிம் டாம் பிக்", "price": 85, "full": 340, "cat": "kids", "tag": "RRR 2026" },
  { "id": 50, "name": "Selfie Stick", "ta": "செல்ஃபி ஸ்டிக்", "price": 180, "full": 720, "cat": "kids", "tag": "RRR 2026" },
  { "id": 51, "name": "Photo Flash", "ta": "போட்டோ ஃபிளாஷ்", "price": 75, "full": 300, "cat": "kids", "tag": "RRR 2026" },
  { "id": 52, "name": "Mini Siren", "ta": "மினி சைரன்", "price": 145, "full": 580, "cat": "kids", "tag": "RRR 2026" },
  { "id": 53, "name": "Mega Siren", "ta": "மெகா சைரன்", "price": 200, "full": 800, "cat": "kids", "tag": "RRR 2026" },
  { "id": 54, "name": "Sword", "ta": "வாள்", "price": 180, "full": 720, "cat": "kids", "tag": "RRR 2026" },
  { "id": 55, "name": "Fish", "ta": "மீன்", "price": 200, "full": 800, "cat": "kids", "tag": "RRR 2026" },
  { "id": 56, "name": "Money Bank Big", "ta": "மணி பேங்க் பிக்", "price": 250, "full": 1000, "cat": "kids", "tag": "RRR 2026" },
  { "id": 57, "name": "Money Bank Small", "ta": "மணி பேங்க் ஸ்மால்", "price": 110, "full": 440, "cat": "kids", "tag": "RRR 2026" },
  { "id": 58, "name": "Butterfly Small Red & Green", "ta": "பட்டாம்பூச்சி ஸ்மால் சிவப்பு பச்சை", "price": 85, "full": 340, "cat": "kids", "tag": "RRR 2026" },
  { "id": 59, "name": "Butterfly Big Red & Green", "ta": "பட்டாம்பூச்சி பிக் சிவப்பு பச்சை", "price": 140, "full": 560, "cat": "kids", "tag": "RRR 2026" },
  { "id": 60, "name": "Bambaram Red & Green", "ta": "பம்பரம் சிவப்பு பச்சை", "price": 120, "full": 480, "cat": "kids", "tag": "RRR 2026" },
  { "id": 61, "name": "Helicopter", "ta": "ஹெலிகாப்டர்", "price": 120, "full": 480, "cat": "kids", "tag": "RRR 2026" },
  { "id": 62, "name": "Colour Smoke", "ta": "கலர் ஸ்மோக்", "price": 200, "full": 800, "cat": "kids", "tag": "RRR 2026" },
  { "id": 63, "name": "Snake Tablet", "ta": "பாம்பு மாத்திரை", "price": 30, "full": 120, "cat": "kids", "tag": "RRR 2026" },
  { "id": 64, "name": "1.5 Twinkling Star Special", "ta": "1.5 ட்விங்க்ளிங் ஸ்டார் ஸ்பெஷல்", "price": 30, "full": 120, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 65, "name": "4 inch Twinkling Star Deluxe", "ta": "4 இன்ச் ட்விங்க்ளிங் ஸ்டார் டீலக்ஸ்", "price": 80, "full": 320, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 66, "name": "7 cm Pencil", "ta": "7 செ.மீ. பென்சில்", "price": 35, "full": 140, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 67, "name": "Colour Crush", "ta": "கலர் க்ரஷ்", "price": 150, "full": 600, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 68, "name": "Navrang Pencil 3 Colour", "ta": "நவரங் பென்சில் 3 கலர்", "price": 180, "full": 720, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 69, "name": "Lala / Loggy / Trix / Minions", "ta": "லாலா / லாக்கி / ட்ரிக்ஸ் / மினியன்ஸ்", "price": 180, "full": 720, "cat": "pencils", "tag": "RRR 2026" },
  { "id": 70, "name": "2¾ Kuruvai 3 ply", "ta": "2¾ குருவி 3 பிளை", "price": 8, "full": 32, "cat": "sound", "tag": "RRR 2026" },
  { "id": 71, "name": "3½ Laxmi Special 5 ply", "ta": "3½ லட்சுமி ஸ்பெஷல் 5 பிளை", "price": 17, "full": 68, "cat": "sound", "tag": "RRR 2026" },
  { "id": 72, "name": "4 Laxmi Special 8 ply", "ta": "4 லட்சுமி ஸ்பெஷல் 8 பிளை", "price": 20, "full": 80, "cat": "sound", "tag": "RRR 2026" },
  { "id": 73, "name": "4 Deluxe Laxmi", "ta": "4 டீலக்ஸ் லட்சுமி", "price": 35, "full": 140, "cat": "sound", "tag": "RRR 2026" },
  { "id": 74, "name": "4 Deluxe Laxmi Electric Fuse", "ta": "4 டீலக்ஸ் லட்சுமி எலக்ட்ரிக் ஃபியூஸ்", "price": 40, "full": 160, "cat": "sound", "tag": "RRR 2026" },
  { "id": 75, "name": "4 Super Deluxe Kannmani 12 ply", "ta": "4 சூப்பர் டீலக்ஸ் கண்ணமணி 12 பிளை", "price": 45, "full": 180, "cat": "sound", "tag": "RRR 2026" },
  { "id": 76, "name": "5 Deluxe Laxmi Electric Fuse", "ta": "5 டீலக்ஸ் லட்சுமி எலக்ட்ரிக் ஃபியூஸ்", "price": 50, "full": 200, "cat": "sound", "tag": "RRR 2026" },
  { "id": 77, "name": "6 Deluxe Laxmi Electric Fuse", "ta": "6 டீலக்ஸ் லட்சுமி எலக்ட்ரிக் ஃபியூஸ்", "price": 60, "full": 240, "cat": "sound", "tag": "RRR 2026" },
  { "id": 78, "name": "3½ Two Sound Bada", "ta": "3½ டூ சவுண்ட் படா", "price": 40, "full": 160, "cat": "sound", "tag": "RRR 2026" },
  { "id": 79, "name": "Red Bijili 50s", "ta": "ரெட் பிஜிலி 50's", "price": 18, "full": 72, "cat": "sound", "tag": "RRR 2026" },
  { "id": 80, "name": "Red Bijili Nandhini", "ta": "ரெட் பிஜிலி நந்தினி", "price": 40, "full": 160, "cat": "sound", "tag": "RRR 2026" },
  { "id": 81, "name": "Red Bijili 100s Vel / TVK / Blue Star / MK", "ta": "ரெட் பிஜிலி 100's", "price": 60, "full": 240, "cat": "sound", "tag": "RRR 2026" },
  { "id": 82, "name": "Red Bijili 100s Krishna", "ta": "ரெட் பிஜிலி 100's கிருஷ்ணா", "price": 70, "full": 280, "cat": "sound", "tag": "RRR 2026" },
  { "id": 83, "name": "28 Chorsa", "ta": "28 சோர்சா", "price": 20, "full": 80, "cat": "sound", "tag": "RRR 2026" },
  { "id": 84, "name": "28 Giant", "ta": "28 ஜெயண்ட்", "price": 25, "full": 100, "cat": "sound", "tag": "RRR 2026" },
  { "id": 85, "name": "56 Giant", "ta": "56 ஜெயண்ட்", "price": 60, "full": 240, "cat": "sound", "tag": "RRR 2026" },
  { "id": 86, "name": "24 Deluxe", "ta": "24 டீலக்ஸ்", "price": 50, "full": 200, "cat": "deluxe", "tag": "RRR 2026" },
  { "id": 87, "name": "50 Deluxe", "ta": "50 டீலக்ஸ்", "price": 110, "full": 440, "cat": "deluxe", "tag": "RRR 2026" },
  { "id": 88, "name": "100 Deluxe", "ta": "100 டீலக்ஸ்", "price": 220, "full": 880, "cat": "deluxe", "tag": "RRR 2026" },
  { "id": 89, "name": "Ganga Jamuna", "ta": "கங்கா ஜமுனா", "price": 100, "full": 400, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 90, "name": "King of King / Kango Bomb", "ta": "கிங் ஆஃப் கிங் / காங்கோ பாம்", "price": 120, "full": 480, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 91, "name": "Classic Bomb", "ta": "கிளாசிக் பாம்", "price": 150, "full": 600, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 92, "name": "Titan Bomb", "ta": "டைட்டன் பாம்", "price": 220, "full": 880, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 93, "name": "Mega Dinousr Bomb Deluxe", "ta": "மெகா டைனோசர் பாம் டீலக்ஸ்", "price": 240, "full": 960, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 94, "name": "Digital Bomb", "ta": "டிஜிட்டல் பாம்", "price": 250, "full": 1000, "cat": "bomb", "tag": "RRR 2026" },
  { "id": 95, "name": "7 Shots Colour Celebration 5 pcs", "ta": "7 ஷாட்ஸ் கலர் செலிபிரேஷன்", "price": 100, "full": 400, "cat": "sky", "tag": "RRR 2026" },
  { "id": 96, "name": "7 Shots 10 pcs", "ta": "7 ஷாட்ஸ் 10 பீஸ்", "price": 200, "full": 800, "cat": "sky", "tag": "RRR 2026" },
  { "id": 97, "name": "Colour Shot SKS 10 pcs", "ta": "கலர் ஷாட் SKS", "price": 175, "full": 700, "cat": "sky", "tag": "RRR 2026" },
  { "id": 98, "name": "Penta or Jehajal 5 Colour", "ta": "பென்டா / ஜெஹாஜல் 5 கலர்", "price": 240, "full": 960, "cat": "sky", "tag": "RRR 2026" },
  { "id": 99, "name": "Chotta Fancy", "ta": "சோட்டா ஃபேன்சி", "price": 40, "full": 160, "cat": "sky", "tag": "RRR 2026" },
  { "id": 100, "name": "Chotta Fancy DSLR 5 in 1", "ta": "சோட்டா ஃபேன்சி DSLR 5 இன் 1", "price": 250, "full": 1000, "cat": "sky", "tag": "RRR 2026" },
  { "id": 101, "name": "Ulta Pulta", "ta": "உல்டா புல்டா", "price": 240, "full": 960, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 102, "name": "Colour Fantasy", "ta": "கலர் ஃபேன்டஸி", "price": 350, "full": 1400, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 103, "name": "Lotus Wheel", "ta": "லோட்டஸ் வீல்", "price": 200, "full": 800, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 104, "name": "Zodi Spinner", "ta": "சோடி ஸ்பின்னர்", "price": 200, "full": 800, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 105, "name": "1.25 Pipe 5 in 1 Multi Colour", "ta": "1.25 பைப் 5 இன் 1 மல்டி கலர்", "price": 800, "full": 3200, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 106, "name": "Roopkheela Flower Pot", "ta": "ரூப்கீலா ஃப்ளவர் பாட்", "price": 600, "full": 2400, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 107, "name": "Varnajal Flower", "ta": "வர்ணஜால் ஃப்ளவர்", "price": 600, "full": 2400, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 108, "name": "Baby Pink 3½ Pipe / Baby Violet", "ta": "பேபி பிங்க் 3½ பைப் / பேபி வயலெட்", "price": 1500, "full": 6000, "cat": "ayya", "tag": "RRR 2026" },
  { "id": 109, "name": "Colour Pinjor Kotti Super / Green Berry Kotti", "ta": "கலர் பிஞ்சோர் கொட்டி சூப்பர் / கிரீன் பெர்ரி கொட்டி", "price": 680, "full": 2720, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 110, "name": "Blue Heaven / Blue Chip 4 inch Pipe Mega", "ta": "ப்ளூ ஹெவன் / ப்ளூ சிப் 4 இன்ச் பைப் மெகா", "price": 1250, "full": 5000, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 111, "name": "4 inch Pipe Great Wall Series", "ta": "4 இன்ச் பைப் கிரேட் வால் சீரிஸ்", "price": 1250, "full": 5000, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 112, "name": "Sports Series", "ta": "ஸ்போர்ட்ஸ் சீரிஸ்", "price": 1250, "full": 5000, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 113, "name": "5 Pipe Happy New Year Family", "ta": "5 பைப் ஹாப்பி நியூ இயர் ஃபேமிலி", "price": 1700, "full": 6800, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 114, "name": "Sizzling Star Tricolour Fountain", "ta": "சிஸ்லிங் ஸ்டார் ட்ரைகலர் ஃபவுண்டன்", "price": 550, "full": 2200, "cat": "sonny", "tag": "RRR 2026" },
  { "id": 115, "name": "Multi Colour Giant Flower Pot", "ta": "மல்டி கலர் ஜெயண்ட் ஃப்ளவர் பாட்", "price": 260, "full": 1040, "cat": "srivijay", "tag": "RRR 2026" },
  { "id": 116, "name": "4 Pipe Varieties", "ta": "4 பைப் வெரைட்டீஸ்", "price": 1100, "full": 4400, "cat": "srivijay", "tag": "RRR 2026" },
  { "id": 117, "name": "5 Pipe Varieties", "ta": "5 பைப் வெரைட்டீஸ்", "price": 1350, "full": 5400, "cat": "srivijay", "tag": "RRR 2026" },
  { "id": 118, "name": "Wow Pink / Wow Orange / Wow Lemon / Wow 7 Colour", "ta": "வாவ் பிங்க் / ஆரஞ்சு / லெமன் / 7 கலர்", "price": 610, "full": 2440, "cat": "srivijay", "tag": "RRR 2026" },
  { "id": 119, "name": "Lunix Rocket", "ta": "லூனிக்ஸ் ராக்கெட்", "price": 160, "full": 640, "cat": "rocket", "tag": "RRR 2026" },
  { "id": 120, "name": "2 Sound Rocket", "ta": "2 சவுண்ட் ராக்கெட்", "price": 170, "full": 680, "cat": "rocket", "tag": "RRR 2026" },
  { "id": 121, "name": "Whistling Rocket", "ta": "விஸ்லிங் ராக்கெட்", "price": 200, "full": 800, "cat": "rocket", "tag": "RRR 2026" },
  { "id": 122, "name": "1¾ Pipe", "ta": "1¾ பைப்", "price": 350, "full": 1400, "cat": "pipe", "tag": "RRR 2026" },
  { "id": 123, "name": "2 Pipe", "ta": "2 பைப்", "price": 400, "full": 1600, "cat": "pipe", "tag": "RRR 2026" },
  { "id": 124, "name": "2 Pipe 6 Varieties Single", "ta": "2 பைப் 6 வெரைட்டீஸ்", "price": 110, "full": 440, "cat": "pipe", "tag": "RRR 2026" },
  { "id": 125, "name": "3V2 Fancy Pipe 4 Varieties", "ta": "3V2 ஃபேன்சி பைப் 4 வெரைட்டீஸ்", "price": 320, "full": 1280, "cat": "pipe", "tag": "RRR 2026" },
  { "id": 126, "name": "2 / 3 Step", "ta": "2 / 3 ஸ்டெப்", "price": 400, "full": 1600, "cat": "pipe", "tag": "RRR 2026" },
  { "id": 127, "name": "12 Shots", "ta": "12 ஷாட்ஸ்", "price": 145, "full": 580, "cat": "multishot", "tag": "RRR 2026" },
  { "id": 128, "name": "12 Shots Red & Green Colour", "ta": "12 ஷாட்ஸ் ரெட் & கிரீன் கலர்", "price": 240, "full": 960, "cat": "multishot", "tag": "RRR 2026" },
  { "id": 129, "name": "25 Shots Raider", "ta": "25 ஷாட்ஸ் ரைடர்", "price": 270, "full": 1080, "cat": "multishot", "tag": "RRR 2026" },
  { "id": 130, "name": "30 Shots Multi Colour Still Stock", "ta": "30 ஷாட்ஸ் மல்டி கலர்", "price": 295, "full": 1180, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 131, "name": "30 Shots Multi Colour Jawa / Prime", "ta": "30 ஷாட்ஸ் மல்டி கலர் ஜாவா / பிரைம்", "price": 550, "full": 2200, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 132, "name": "30 Shots Multi Colour Crackling AK", "ta": "30 ஷாட்ஸ் மல்டி கலர் கிராக்கிளிங் AK", "price": 650, "full": 2600, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 133, "name": "60 Shots", "ta": "60 ஷாட்ஸ்", "price": 1100, "full": 4400, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 134, "name": "120 Shots Special Multi Colour", "ta": "120 ஷாட்ஸ் ஸ்பெஷல் மல்டி கலர்", "price": 2000, "full": 8000, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 135, "name": "240 Shots", "ta": "240 ஷாட்ஸ்", "price": 4000, "full": 16000, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 136, "name": "500 Shots", "ta": "500 ஷாட்ஸ்", "price": 8000, "full": 32000, "cat": "multishot", "tag": "RRR 2026", "maxQty": 1 },
  { "id": 137, "name": "Max 3 in 1 Cone Ramesh", "ta": "மேக்ஸ் 3 இன் 1 கோன் ரமேஷ்", "price": 40, "full": 160, "cat": "matches", "tag": "RRR 2026" },
  { "id": 138, "name": "V.I.P. 10 in 1 Laptop Mega Ramesh", "ta": "V.I.P. 10 இன் 1 லேப்டாப் மெகா ரமேஷ்", "price": 280, "full": 1120, "cat": "matches", "tag": "RRR 2026" },
  { "id": 139, "name": "Gift Box 21 Items", "ta": "கிஃப்ட் பாக்ஸ் 21 வகைகள்", "price": 499, "full": 1999, "cat": "gift", "tag": "RRR 2026" },
  { "id": 140, "name": "Gift Box 25 Items", "ta": "கிஃப்ட் பாக்ஸ் 25 வகைகள்", "price": 699, "full": 2799, "cat": "gift", "tag": "RRR 2026" },
  { "id": 141, "name": "Gift Box 30 Items", "ta": "கிஃப்ட் பாக்ஸ் 30 வகைகள்", "price": 899, "full": 3599, "cat": "gift", "tag": "RRR 2026" },
  { "id": 142, "name": "Gift Box 40 Items", "ta": "கிஃப்ட் பாக்ஸ் 40 வகைகள்", "price": 1299, "full": 5199, "cat": "gift", "tag": "RRR 2026" },
  { "id": 143, "name": "Gift Box 45 Items", "ta": "கிஃப்ட் பாக்ஸ் 45 வகைகள்", "price": 1499, "full": 5999, "cat": "gift", "tag": "RRR 2026" },
  { "id": 144, "name": "Gift Box 50 Items", "ta": "கிஃப்ட் பாக்ஸ் 50 வகைகள்", "price": 1899, "full": 7599, "cat": "gift", "tag": "RRR 2026" },
  { "id": 145, "name": "100 Series", "ta": "100 சீரிஸ்", "price": 45, "full": 180, "cat": "series", "tag": "RRR 2026" },
  { "id": 146, "name": "200 Series", "ta": "200 சீரிஸ்", "price": 100, "full": 400, "cat": "series", "tag": "RRR 2026" },
  { "id": 147, "name": "1K Series", "ta": "1K சீரிஸ்", "price": 200, "full": 400, "cat": "series", "tag": "RRR 2026" },
  { "id": 148, "name": "2K Series", "ta": "2K சீரிஸ்", "price": 400, "full": 800, "cat": "series", "tag": "RRR 2026" },
  { "id": 149, "name": "5K Series", "ta": "5K சீரிஸ்", "price": 1000, "full": 2000, "cat": "series", "tag": "RRR 2026" },
  { "id": 150, "name": "10K Series", "ta": "10K சீரிஸ்", "price": 2000, "full": 4000, "cat": "series", "tag": "RRR 2026" },
  { "id": 151, "name": "Paper Bomb Small ¼", "ta": "பேப்பர் பாம் ஸ்மால் ¼", "price": 50, "full": 200, "cat": "paper", "tag": "RRR 2026" },
  { "id": 152, "name": "Paper Bomb Medium ½", "ta": "பேப்பர் பாம் மீடியம் ½", "price": 100, "full": 400, "cat": "paper", "tag": "RRR 2026" },
  { "id": 153, "name": "Paper Bomb Mega 1", "ta": "பேப்பர் பாம் மெகா 1", "price": 200, "full": 800, "cat": "paper", "tag": "RRR 2026" },
  { "id": 154, "name": "Ring Gun with Cap", "ta": "ரிங் கன் வித் கேப்", "price": 110, "full": 440, "cat": "toy", "tag": "RRR 2026" },
  { "id": 155, "name": "Ring Gun", "ta": "ரிங் கன்", "price": 80, "full": 320, "cat": "toy", "tag": "RRR 2026" },
  { "id": 156, "name": "Roll Cap", "ta": "ரோல் கேப்", "price": 90, "full": 360, "cat": "toy", "tag": "RRR 2026" },
  { "id": 157, "name": "Enu Big / Gusher / Exo", "ta": "எனு பிக் / கஷர் / எக்ஸோ", "price": 80, "full": 320, "cat": "toy", "tag": "RRR 2026" },
  { "id": 158, "name": "Ziraffe Black / Dragon Colour / Turbo Colour", "ta": "ஜிராஃப் பிளாக் / டிராகன் கலர் / டர்போ கலர்", "price": 65, "full": 260, "cat": "toy", "tag": "RRR 2026" },
  { "id": 159, "name": "Ziraffe Colour / Accord / Selvo / Jick Colour", "ta": "ஜிராஃப் கலர் / அக்கார்ட் / செல்வோ / ஜிக் கலர்", "price": 95, "full": 380, "cat": "toy", "tag": "RRR 2026" },
  { "id": 160, "name": "Jick Black / Gemini Zick / P (56)", "ta": "ஜிக் பிளாக் / ஜெமினி ஜிக் / P (56)", "price": 70, "full": 280, "cat": "toy", "tag": "RRR 2026" },
  { "id": 161, "name": "Cenzo / Gusher Small / Luger", "ta": "சென்சோ / கஷர் ஸ்மால் / லூகர்", "price": 75, "full": 300, "cat": "toy", "tag": "RRR 2026" },
  { "id": 162, "name": "Spencer / Dragan Colour", "ta": "ஸ்பென்சர் / டிராகன் கலர்", "price": 100, "full": 400, "cat": "toy", "tag": "RRR 2026" }
];

export function getProductImage(product) {
  if (product.customImage) return product.customImage;
  const categoryInfo = CATEGORY_MAP[product.cat];
  if (categoryInfo && categoryInfo.image) {
    return categoryInfo.image;
  }
  return images.sparklers;
}